[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'flazz/vim-colorschemes'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'sjl/gundo.vim'

# [[plugins]]
# repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]]
repo = 'bling/vim-airline'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'ntpeters/vim-better-whitespace'

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'nvie/vim-flake8'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'valloric/youcompleteme'

[[plugins]]
repo = 'SirVer/ultisnips'

[[plugins]]
repo = 'honza/vim-snippets'

[[plugins]]
repo = 'jmcomets/vim-pony'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'scrooloose/nerdcommenter'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'https://github.com/slim-template/vim-slim'

[[plugins]]
repo = 'https://github.com/tpope/vim-rails'

[[plugins]]
repo = 'neomake/neomake'
